import { MetadataRoute } from 'next';
import { APP_CONFIG } from '~/helpers/config';
import { color } from '~/theme/variables/palette';

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: APP_CONFIG.NAME,
    short_name: APP_CONFIG.NAME,
    description:
      'Phim cập nhập liên tục từng ngày, mời các bạn cùng thưởng thức những bộ phim hành động, võ thuật, phim chiếu rạp, các thể loại phim tâm lý, tình cảm cực lôi cuốn và hấp dẫn nhất.',
    categories: [
      'movie',
      'learning english',
      'tv show',
      'anime',
      'cartoon',
      'music',
      'game',
      'sport',
      'news',
      'technology',
      'science',
      'documentary',
      'travel',
      'food',
      'health',
      'lifestyle',
      'fashion',
      'comedy',
      'entertainment',
      'kids',
      'horror',
      'drama',
      'action',
      'adventure',
      'romance',
      'thriller',
      'crime',
      'mystery',
      'fantasy',
      'superhero',
      'sci-fi',
      'history',
      'war',
      'western',
      'musical',
      'biography',
      'reality-tv',
      'talk-show',
      'game-show',
      'sporting-event',
      'awards-show',
      'news',
      'politics',
      'religion',
      'soap',
      'reality',
      'variety',
      'sitcom',
      'family',
      'animation',
      'anime',
      'cartoon',
      'short',
      'experimental',
      'music-video',
      'travel',
      'food',
      'health',
      'lifestyle',
      'fashion',
      'comedy',
      'entertainment',
      'kids',
      'horror',
      'drama',
      'action',
      'adventure',
      'romance',
      'thriller',
      'crime',
      'mystery',
      'fantasy',
      'superhero',
      'sci-fi',
      'history',
      'war',
      'western',
      'musical',
      'biography',
      'reality-tv',
      'talk-show',
      'game-show',
      'sporting-event',
      'awards-show',
      'news',
      'politics',
      'religion',
      'soap',
      'reality',
      'variety',
      'sitcom',
      'family',
      'animation',
      'anime',
      'cartoon',
      'short',
      'experimental',
      'music-video',
      'travel',
      'food',
      'health',
      'lifestyle',
      'fashion',
      'comedy',
      'entertainment',
      'kids',
      'horror',
      'drama',
      'action',
      'adventure',
      'romance',
      'thriller',
      'crime',
      'mystery',
      'fantasy',
      'superhero',
      'sci-fi',
      'history',
      'war',
      'western',
      'musical',
      'biography',
      'reality-tv',
      'talk-show',
      'game-show',
      'sporting-event',
      'awards-show',
      'news',
      'politics',
      'religion',
      'soap',
      'reality',
      'variety',
      'sitcom',
      'family',
      'animation',
      'anime',
      'cartoon',
      'short',
      'experimental',
      'music-video',
    ],
    start_url: '/',
    id: '/',
    display: 'standalone',
    background_color: color.black,
    theme_color: color.red,
    icons: [
      {
        src: '/favicon-16x16.png',
        sizes: '16x16',
        type: 'image/png',
      },
      {
        src: '/favicon-32x32.png',
        sizes: '32x32',
        type: 'image/png',
      },
      {
        src: '/favicon.ico',
        sizes: '48x48',
        type: 'image/ico',
      },
      {
        src: '/apple-touch-icon.png',
        sizes: 'any',
        type: 'image/png',
      },
      {
        src: '/android-chrome-192x192.png',
        sizes: '192x192',
        type: 'image/png',
      },
      {
        src: '/android-chrome-512x512.png',
        sizes: '512x512',
        type: 'image/png',
      },
    ],
    scope: '/',
  };
}
